version: "3.7"

services:
  app:
    build: .
    container_name: rentx
    restart: always
    volumes:
      - .:/usr/app/
      -   /usr/app/node_modules/
    depends_on:
      - database
    networks:
      - app-connect
    ports:
      - '3333:3333'


  database:
    image: postgres
    container_name: database
    restart: always
    environment:
      POSTGRES_USER: 'docker'
      POSTGRES_PASSWORD: 'ignite'
      POSTGRES_DB: 'rentx'
    volumes:
      - pgdata:/data/postgres
    networks:
      - app-connect
    ports:
      - '5432:5432'

  # redis:
  #   image: redis:alpine
  #   ports:
  #     - 6379:6379
  
volumes: 
  pgdata:
    driver: local

networks:
  app-connect:
      driver: bridge